version: '3'
services:
  supermarkt-generator:
    build:
      context: .
      dockerfile: docker/Dockerfile-generate
    image: supermarkt
    container_name: supermarkt-generator
    volumes:
      - ./data/csv_data:/app/csv_data

  datenbank:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: meine-datenbank
      POSTGRES_USER: mein-benutzer
      POSTGRES_PASSWORD: mein-passwort
    ports:
      - "5432:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile-airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data/csv_data:/app/csv_data
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - datenbank
    networks:
      - airflow-net

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile-airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data/csv_data:/app/csv_data
    command: scheduler
    depends_on:
      - datenbank
    networks:
      - airflow-net

networks:
  airflow-net:

