# Import data to MySQL
# Dieser Service ist dafür verantwortlich, die generierten Daten in die MySQL-Datenbank zu importieren.
# Er verwendet ein offizielles Python-Image als Basis.
FROM python:3.9-slim

# Setzt /app als Verzeichnis, in dem die Containerbefehle ausgeführt werden.
WORKDIR /app

# Kopiert das wait-for-it.sh-Skript in den Container und setzt die Ausführungsrechte
COPY wait-for-it.sh /app/wait-for-it.sh

# Installiert die erforderlichen Pakete
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y netcat-traditional dos2unix
RUN pip install mysql-connector-python

# Konvertiert die Skripte, um Windows-Zeilenumbrüche zu entfernen
RUN dos2unix /app/wait-for-it.sh

# Kopiert das Python-Skript zum Importieren von Daten
COPY import_to_mysql.py /app/
RUN dos2unix /app/import_to_mysql.py

# Setzt die Ausführungsrechte für das wait-for-it.sh-Skript
RUN chmod +x /app/wait-for-it.sh

# Diese Zeile sorgt dafür, dass das Python import Skript erst dann startet wenn die Datenbank auf Port 3306 erreichbar ist.
# Das reine "depends on" im compose File reicht nicht aus, da alle Container parallel starten.
CMD ["/app/wait-for-it.sh", "mysql_db:3306", "--", "python3", "/app/import_to_mysql.py"]