FROM jupyter/pyspark-notebook

# Als root ausführen
USER root

# System-Utilities aktualisieren
RUN apt-get update && apt-get upgrade -y

# Installieren der notwendigen Pakete für MySQL-Verbindungen
RUN apt-get install -y mysql-client unzip

# MySQL JDBC Treiber installieren
RUN wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.26.zip -O /tmp/mysql-connector-java.zip && \
    unzip /tmp/mysql-connector-java.zip -d /tmp && \
    cp /tmp/mysql-connector-java-8.0.26/mysql-connector-java-8.0.26.jar $SPARK_HOME/jars/

# Installieren des mysql-connector-python Pakets mit pip3
RUN pip3 install mysql-connector-python


# Spark-Skript und wait-for-import hinzufügen
COPY spark_aggregate.py /app/spark_aggregate.py
COPY wait-for-import.sh /app/wait-for-import.sh

# Berechtigungen für das Skript setzen und als Eintrittspunkt verwenden
RUN chmod +x /app/wait-for-import.sh
CMD ["/app/wait-for-import.sh", "spark-submit", "/app/spark_aggregate.py"]
