# Verwenden Sie ein offizielles Python-Image als Basis
FROM python:3.9

# Setzen Sie das Arbeitsverzeichnis innerhalb des Containers
WORKDIR /app

# Kopieren Sie das Python-Skript in das Arbeitsverzeichnis des Containers
COPY . /app/

# Installieren Sie die PostgreSQL-Bibliothek
RUN pip install psycopg2-binary

# Installieren Sie das Pandas-Modul
RUN pip install pandas

# Führen Sie das Python-Skript beim Containerstart aus
CMD ["python3", "ingestion.py"]
