# Verwenden Sie ein offizielles Python-Image als Basis
FROM python:3.9

# Setzen Sie das Arbeitsverzeichnis innerhalb des Containers
WORKDIR /app

# Kopieren Sie nur das notwendige Python-Skript in das Arbeitsverzeichnis
COPY generate_supermarkt_daten.py /app/

# Führen Sie die Python-Anwendung alle 90 Tage in einer Endlosschleife aus
CMD while true; do python3 generate_supermarkt_daten.py; sleep 7776000; done
