version: '3.8'

services:
  # Supermarkt Data Generator
  supermarkt_data_gen:
    build:
      context: .
      dockerfile: Dockerfile-generate
    volumes:
      - data-volume:/app/csv_data

  # MySQL Database
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermarkt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Hinzufügen dieser Zeile

  # Import data to MySQL
  data_importer:
    build:
      context: .
      dockerfile: Dockerfile-import
    depends_on:
      - supermarkt_data_gen
      - mysql_db
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: rootpassword
      DB_NAME: supermarkt_db
    volumes:
      - data-volume:/app/csv_data

volumes:
  mysql-data:
  data-volume:
