# Basis-Image mit Airflow
FROM apache/airflow:2.2.2-python3.9

# Argument für die Airflow-Version
ARG AIRFLOW_VERSION=2.2.2

# Umgebungsvariablen setzen
ENV AIRFLOW_HOME=/usr/local/airflow
ENV AIRFLOW_DEPS=""

# Airflow benötigt dieses Verzeichnis
USER root
RUN mkdir -p $AIRFLOW_HOME \
    && chown -R airflow: $AIRFLOW_HOME

# Zurück zu airflow-User wechseln
USER airflow

# Installieren Sie zusätzliche Abhängigkeiten und Python-Bibliotheken, falls erforderlich
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir 'apache-airflow['$AIRFLOW_DEPS']'==$AIRFLOW_VERSION

# Setzen Sie das Standardkommando auf Airflow webserver
CMD ["airflow", "webserver"]
